run_id: 01
model_name: clone_and_false_positives
train_filename: train.csv
val_filename: val.csv
test_filename: main.csv
model_save_root: ../../models/
batch_size: 128
early_stopping_patience: 10
log_dir: ../../logs/
pretrained_embeddings_file_path: ../../data/external/bcb/embeddings.8d.txt
reweight_predictions_for_kaggle: false
save_period: 250
rnn_hidden_size: 256
share_encoder_weights: true
num_epochs: 8
output_keep_prob: 1
val_period: 250
fine_tune_embeddings: false
log_period: 10
word_embedding_dim: 8
rnn_output_mode: last
num_sentence_words: 300
